spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/voidlight
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret: change-me-please-change-me-please-change
